spring.application.name=user-service
server.port=8090

spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
spring.security.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#Testing
# Use in-memory H2 database
spring.datasource.url=jdbc:h2:mem:user_service_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
# Automatically create and update the database schema
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.ai.openai.api-key=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